console.log("Hola compañeros, estas son las instrucciones para lavar un vaso")
console.log("a) agarrar el vaso sucio")
console.log("b) ir a la pileta")
console.log("c) ponerle deterjente a la espona")
console.log("d) abrir la canilla")
console.log("e) mojar la esponja")
console.log("f) mojar el interior y exterior del vaso")
console.log("g) pasar la esponja con detergente por el interior y exterior del vaso")
console.log("h) enjuagar el detergente con agua")
console.log("i) colocar el vaso en el secaplatos ")
